version: 1.2
workflows:
  - subclass: WDL
    name: PharmCAT-Pipeline
    primaryDescriptorPath: /dockstore/pipeline/PharmCAT_Pipeline.wdl
    readMePath: /pipeline/README.md
    filters:
      tags:
        - /v\d+.*/
