MAKEFLAGS = -j1

# Determine this makefile's path.
# Be sure to place this BEFORE `include` directives, if any.
THIS_FILE := $(lastword $(MAKEFILE_LIST))

ifeq ($(OS),Windows_NT)
	GRADLE_CMD := cmd /c gradlew.bat
else
	GRADLE_CMD := ./gradlew
endif


.PHONY: vcfTests
vcfTests:
	${GRADLE_CMD} clean
	rm -rf build/testVcf build/autogeneratedTestResults build/pharmcat_positions.vcf
	${GRADLE_CMD} extractPositionsForTest
	src/scripts/generate_vcf_test_data.sh
	${GRADLE_CMD} testAutogeneratedVcfs
	cd build; zip -r vcfTest-`date +'%Y-%m-%d'`.zip autogeneratedTestResults

.PHONY: updateData
updateData:
	${GRADLE_CMD} clean
	rm -f build/positions_reference.tsv
	${GRADLE_CMD} updateData
	${GRADLE_CMD} extractPositions
	if [ -f "build/positions_reference.tsv" ]; then \
	  cp build/positions_reference.tsv src/main/resources/org/pharmgkb/pharmcat/definition; \
	fi
