source 'https://rubygems.org'

gem "bundler", ">=2.4.19"
gem "jekyll", ">=4.3.2"
gem "jemoji", "~> 0.13.0"
gem "just-the-docs", "0.6.1"
gem "kramdown-parser-gfm", ">=1.1.0"
gem "rouge", ">=4.1.3"
gem "escape_utils", ">=1.3.0"

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
